### ISSUE TITLE
Binmode not needed

### ISSUE THREAD

**Issue by Digicrat** [beanz/device-rfxcom-perl#3]
This package seems to be broken.  Running a sample RX, I get an error about binmode in Device::SerialPort.

According to the Device::SerialPort documentation, "Ports are opened for binary transfers. A separate binmode is not needed."

Therefore I've commented out the binmode call on line 123 of Device/RFXCOM/Base.pm

On an unrelated note, it looks like this library only supports 2 of the many protocols provided by RFX433, besides not being updated in a number of years.  I would try adding support for the devices I need, but I can't actually locate any documentation on the RFX433's API/interface despite its relative popularity . . .

**Comment by beanz** [comment]
Fixed. (And released). Thanks.
